#################################################
# DriveBackupV2   -   by Max Maeder (MaxTheGinus)
#################################################

# DOCUMENTATION HAS MOVED
# Now available online at: https://github.com/MaxMaeder/DriveBackupV2/wiki

delay: 60
backup-thread-priority: 1
keep-count: 20
local-keep-count: 0
zip-compression: 1
backups-require-players: true
disable-saving-during-backups: true

scheduled-backups: false
backup-schedule-list:

backup-list:
- path: "world"
  format: "Backup-world-%FORMAT.zip"
  create: true
- path: "plugins"
  format: "Backup-plugins-%FORMAT.zip"
  create: true

external-backup-list:

dir: "backups"

destination: "backups"

googledrive:
  enabled: false
onedrive:
  enabled: false
dropbox:
  enabled: false
ftp:
  enabled: false
  hostname: "ftp.example.com"
  port: 21
  sftp: false
  ftps: false
  username: "Username"
  password: 
  sftp-public-key: 
  sftp-passphrase: 
  working-dir:

messages:
  send-in-chat: true
  prefix: "&6[&4DriveBackupV2&6] "
  default-color: "&3"

advanced:
  metrics: true
  update-check: true
  suppress-errors: false
  date-language: "en"
  date-format-timezone: "-00:00"
  ftp-file-separator: "/"